spring:
  application:
    # 具体代码调用，请看 \sea-web-shop\src\main\java\pers\zb\web\shop\controller\ShopController.java 中的router方法；
    name: cloud-bless-service-music # 服务提供者的应用服务名称（服务调用者是通过调用此服务名（cloud-bless-service-music）来实现服务调用的，与域名和端口号没有关系了）

eureka:
  instance:
    hostname: localhost # 服务提供者应用所在的主机（本地测试的话，使用localhost或者127.0.0.1即可，或者在host文件中指定一个虚拟域名也可以）
    lease-renewal-interval-in-seconds: 5 # 心跳时间，表示eureka client发送心跳给eureka server端的频率（缺省为30s）
  client:
    service-url:
      defaultZone: http://server.eureka.slave1.com:18761/eureka,http://server.eureka.slave2.com:28761/eureka # 指定eureka服务器集群列表地址


  ############################################################
  #
  # mysql
  #
  ############################################################
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/cloud-bless
#    username: root
#    password: root123456
#    driver-class-name: com.mysql.jdbc.Driver
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#   配置数据源

#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
#    url: jdbc:mysql://localhost:3306/cloud-bless
#    username: root
#    password: root123456
#    driver-class-name: com.mysql.jdbc.Driver
#  # hbm2ddl 数据表和实体类映射生成配置
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org,springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# 日志配置
logging:
  level:
    xin.spring.bless.cloud.bless: debug
    org.springframework: warn


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: xin.spring.bless.cloud.bless.common.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
debug: true
